---
- name: Setup Workstation
  hosts: localhost
  #become: true
  gather_facts: true

  #vars_files:
    #- vars/vars.yml
    #- vars/vault_vars.yml

  tasks:
    - include_tasks: tasks/setup.yml
    - include_tasks: tasks/repos.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/azure.yml
    - include_tasks: tasks/aws.yml
    - include_tasks: tasks/terraform.yml
    - include_tasks: tasks/networktools.yml
    - include_tasks: tasks/decorations.yml


  handlers:
#- include_tasks: handlers/main.yml
