---
# Run with ansible-playbook -v ./setup_workstation.yml --ask-become-pass

- name: Setup Workstation
  hosts: localhost
  gather_facts: true
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python
    user_home_directory: /home/alistair
    fastmirror: present

    #include_vars:
        #dir: vars/all

  tasks:
    - debug: var=ansible_facts
    - name: Set package variables
      include_vars: vars/vars.yml
    #- include_tasks: tasks/systemprep.yml
    #- include_tasks: tasks/common.yml
    #- include_tasks: tasks/fedorarepos.yml
      #when: ansible_os_family == "RedHat"
    #- include_tasks: tasks/suserepos.yml
      #when: ansible_os_family == "Suse"
    #- include_tasks: tasks/susekderepos.yml
      #when: 
        #- ansible_facts['distribution_file_variety'] == "SUSE"
        #- ansible_facts['distribution'] != "openSUSE Tumbleweed"
        #- updatekde == yes
    #- include_tasks: tasks/redhatpackages.yml
      #when: ansible_os_family == "RedHat"
    #- include_tasks: tasks/susepackages.yml
      #when: ansible_os_family == "Suse"
    #- include_tasks: tasks/mxlinuxpackages.yml
      #when: ansible_os_family == "Debian"
    #- include_tasks: tasks/snaps.yml
    #- include_tasks: tasks/fonts.yml
      #when: (ansible_os_family == "RedHat") or (ansible_os_family == "Suse")
    #- include_tasks: tasks/azure.yml
    #- include_tasks: tasks/aws.yml
    #- include_tasks: tasks/terraform.yml
    #- include_tasks: tasks/networktools.yml
    #- include_tasks: tasks/decorations.yml
    #- include_tasks: tasks/firefoxextensions.yml
    #- include_tasks: tasks/main.yml
    #- include_tasks: tasks/LFSrequired.yml
    
  handlers:
    #- include_tasks: handlers/main.yml
