---
# Run with ansible-playbook -v ./setup_workstation.yml --ask-become-pass

# Note - If using Ansible < 2.4 installing the Pyrapus Icons will cause issues - see this bug report https://github.com/ansible/ansible/issues/23902

# You will need to have Ansible > 2.4 and (on SuSE) python-xml installed before running the script.

- name: Setup Workstation
  hosts: localhost
  gather_facts: true
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python
    user_home_directory: /home/alistair
    fastmirror: present
    distributionpath: "tasks/{{ distribution_file_variety }}/{{ distribution }}"

  tasks:
    - debug: var=ansible_facts
    - name: Set package variables
      include_vars: vars/vars.yml
      
    # - include_tasks: tasks/commonpackages.yml

    - include_tasks: tasks/susekderepos.yml
      when: 
        - ansible_facts['distribution_file_variety'] == "SUSE"
        - ansible_facts['distribution'] != "openSUSE Tumbleweed"
        - update_kde == "yes"

    # - include_tasks: tasks/browsers.yml
    
    # - include_tasks: tasks/fonts.yml
    
    # - include_tasks: tasks/editors.yml

    # - include_tasks: tasks/aws.yml
    #   when: (awscli == "present" or boto == "present")

    # - include_tasks: tasks/azure.yml
    #   when: (azure_cli == "present")

    # - include_tasks: tasks/gcp.yml
    #   when: (google_cloud_sdk == "present")

    # - include_tasks: tasks/terraform.yml
    #   when: (terraform == "present")

    # - include_tasks: tasks/networktools.yml
    
# KDE Themes, Icons and Decorations


    - include_tasks: tasks/wallpapers.yml
    
    #- include_tasks: tasks/icons.yml - This needs work
    
    - include_tasks: tasks/themes.yml
    

    #- include_tasks: tasks/firefoxextensions.yml
    #- include_tasks: tasks/main.yml
    #- include_tasks: tasks/LFSrequired.yml
    
  handlers:
    #- include_tasks: handlers/main.yml
    
    
    #Old stuff
    
        #- include_tasks: tasks/fedorarepos.yml
      #when: ansible_os_family == "RedHat"
    #- include_tasks: tasks/suserepos.yml
      #when: ansible_os_family == "Suse"
    #- include_tasks: tasks/suseleap15nonossrepos.yml
      #when: 
        #- ansible_facts['distribution_file_variety'] == "SUSE"
        #- ansible_facts['distribution'] != "openSUSE Tumbleweed"
    #- include_tasks: tasks/susekderepos.yml
      #when: 
        #- ansible_facts['distribution_file_variety'] == "SUSE"
        #- ansible_facts['distribution'] != "openSUSE Tumbleweed"
        #- updatekde == yes
    #- include_tasks: tasks/redhatpackages.yml
      #when: ansible_os_family == "RedHat"
    #- include_tasks: tasks/susepackages.yml
      #when: ansible_os_family == "Suse"
    #- include_tasks: tasks/mxlinuxpackages.yml
      #when: ansible_os_family == "Debian"
    #- include_tasks: tasks/snaps.yml
