---

  - name: Import the RPM key for the YUM repository
    rpm_key:
      state: present
      key: http://apt.sw.be/RPM-GPG-KEY.dag.txt
    when: (ansible_facts['os_family'] == "RedHat" and azure_cli == "present")
    
  - name: Add Azure CLI YUM Repository for Red Hat
    yum_repository:
      name: azure-cli
      description: Azure CLI
      baseurl: https://packages.microsoft.com/keys/microsoft.asc
      #gpgcheck: no
    when: (ansible_facts['os_family'] == "RedHat" and azure_cli == "present")
    
# Experiment to see if importing the RPMkey woorks for Suse

  - name: Import the RPM key for the Zypper repository
    rpm_key:
      state: present
      key: http://apt.sw.be/RPM-GPG-KEY.dag.txt
    when: (ansible_facts['os_family'] == "Suse" and azure_cli == "present")

  - name: Add Azure CLI Zypper Repository for Suse
    become: yes
    zypper_repository:
      repo: https://packages.microsoft.com/yumrepos/azure-cli
      name: azure-cli
      description: Azure CLI
      #disable_gpg_check: yes
      overwrite_multiple: yes
      runrefresh: yes
      state: present
      enabled: yes
    when: (ansible_facts['os_family'] == "Suse" and azure_cli == "present")
    
  - name: Add an Apt signing key for Azure CLI, for KDE neon
    become: yes
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
    when:
      - ansible_facts['distribution'] == "KDE neon"
      - azure_cli == "present"

  - name: Add Apt Azure CLI Repository for KDE neon
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main
      state: present
      update_cache: yes
      validate_certs: no
      filename: azure-cli
    when:
      - ansible_facts['distribution'] == "KDE neon"
      - azure_cli == "present"

  - name: Install Azure CLI
    become: yes
    ignore_errors: yes
    package:
      name: azure-cli
      state: "{{ azure_cli }}"
