  - name: Install Firefox
    become: yes
    ignore_errors: yes
    package:
      name: firefox
      state: present
  - name: Install Falkon
    become: yes
    ignore_errors: yes
    package:
      name: falkon
      state: "{{ falkon }}"
  - name: Install Chromium
    become: yes
    ignore_errors: yes
    package:
      name: chromium
      state: "{{ chromium }}"
  - name: Install Opera Browser
    become: yes
    ignore_errors: yes
    package:
      name: opera
      state: "{{ opera }}"
  - name: Install Vivaldi Browser
    become: yes
    ignore_errors: yes
    package:
      name: vivaldi-stable
      state: "{{ vivaldi }}"
  - name: Install Brave Browser
    become: yes
    ignore_errors: yes
    package:
      name: brave-browser
      state: "{{ brave-browser }}"
  - name: Install Brave Keyring
    become: yes
    ignore_errors: yes
    package:
      name: brave-keyring
      state: "{{ brave-browser }}"
