---

# Common Packages

  - name: Install Fast Mirror - fails on Ubuntu but not critical
    become: yes
    ignore_errors: yes
    package:
      name: yum-fastestmirror
      state: present
    when: ansible_facts['os_family'] != "Debian"
    
      
  - name: Install Python bindings for SELinux - needed for some later stages to work on Red Hat systems
    become: yes
    ignore_errors: yes
    package:
      name: libselinux-python
      state: present
    when: ansible_facts['os_family'] == "RedHat"
    
  - name: Install python-xml for Suse - needed for some later stages to work on SuSE systems
    become: yes
    ignore_errors: yes
    package:
      name: python-xml
      state: present
    when: ansible_facts['distribution_file_variety'] == "SUSE"
      
  - name: Install Curl
    become: yes
    ignore_errors: yes
    package:
      name: curl
      state: "present"
    when: (curl == "present" or ansible_facts['distribution'] == "KDE neon" or ansible_facts['distribution'] == "Ubuntu")
    
  - name: Install Git
    become: yes
    ignore_errors: yes
    package:
      name: git
      state: "{{ git }}"

  - name: Install HTOP
    become: yes
    ignore_errors: yes
    package:
      name: htop
      state: "{{ htop }}"

  - name: Install Python PIP
    become: yes
    ignore_errors: yes
    package:
      name: python-pip
      state: "present"
    when: ansible_facts['os_family'] != "Debian"
      
  - name: Install Python PIP
    become: yes
    ignore_errors: yes
    package:
      name: python3-pip
      state: "present"
    when: ansible_facts['os_family'] == "Debian"
      
  - name: Install Latte Dock
    become: yes
    ignore_errors: yes
    package:
      name: latte-dock
      state: "present"
      
  - name: Install Tilix
    become: yes
    ignore_errors: yes
    package:
      name: tilix
      state: "present"
      
  - name: Install yum utils for Fedora / RHEL
    become: yes
    ignore_errors: yes
    package:
      name: yum-utils
      name: dnf-plugins-core
      state: present
    when:
      - ansible_facts['os_family'] == "RedHat"
      
# The following are needed for Microsoft packages on Ubuntu / apt based systems, I've chosen to install them as core packages.
    
  - name: Install KDE Neon / Ubuntu Core Packages
    become: yes
    ignore_errors: yes
    package:
      name: 
      - lsb-release
      - apt-transport-https
      - gpg
      state: "present"
    when: ansible_facts['os_family'] == "Debian"
