
    - name: Install Kate Editor
      become: yes
      ignore_errors: yes
      package:
        name: kate
        state: "{{ kate }}"

    - name: Add VS Code YUM Repository for RHEL / Fedora
      become: yes
      yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: no
      when: (ansible_facts['os_family'] == "RedHat" and vs_code == "present")

    - name: Add VS Code Zypper Repository for Suse
      become: yes
      zypper_repository:
        repo: https://packages.microsoft.com/yumrepos/vscode
        name: vscode
        description: Visual Studio Code
        disable_gpg_check: yes
        overwrite_multiple: yes
        runrefresh: yes
        state: present
        enabled: yes
      when: (ansible_facts['os_family'] == "Suse" and vs_code == "present")

    - name: Add an Apt signing key for VS Code, for KDE neon / Ubuntu
      become: yes
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      when:
        - ( ansible_facts['distribution'] == "KDE neon" or ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"  )
        - vs_code == "present"

    - name: Add Apt VS Code Repository for KDE neon / Ubuntu
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
        update_cache: yes
        validate_certs: no
        filename: vscode
      when:
        - ( ansible_facts['distribution'] == "KDE neon" or ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"  )
        - vs_code == "present"

    - name: Install Microsoft VS Code
      become: yes
      ignore_errors: yes
      package:
        name: code
        state: "{{ vs_code }}"

    - name: Add Atom YUM Repository for RHEL / Fedora
      become: yes
      vars:
        rpmurl: "https://packagecloud.io/AtomEditor/atom/el/7/x86_64"
      yum_repository:
        name: Atom
        description: Atom Editor
        baseurl: "{{ rpmurl }}"
        gpgcheck: no
      when: (ansible_facts['os_family'] == "RedHat" and atom == "present")

    - name: Add Atom Zypper Repository for Suse
      vars:
        rpmurl: "https://packagecloud.io/AtomEditor/atom/el/7/x86_64"
      become: yes
      zypper_repository:
        repo: "{{ rpmurl }}"
        name: Atom
        description: Atom Editor
        disable_gpg_check: yes
        overwrite_multiple: yes
        runrefresh: yes
        state: present
        enabled: yes
      when: (ansible_facts['os_family'] == "Suse" and atom == "present")

    - name: Add an Apt signing key for Atom, for KDE neon / Ubuntu
      become: yes
      apt_key:
        url: https://packagecloud.io/AtomEditor/atom/gpgkey
        state: present
      when:
        - ( ansible_facts['distribution'] == "KDE neon" or ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"  )
        - atom == "present"

    - name: Add Apt Atom Repository for KDE neon / Ubuntu
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
        state: present
        update_cache: yes
        validate_certs: no
        filename: atom
      when:
        - ( ansible_facts['distribution'] == "KDE neon" or ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"  )
        - atom == "present"

    - name: Install Atom Editor
      become: yes
      ignore_errors: yes
      package:
        name: atom
        state: "{{ atom }}"
