---

  - name: Install xorg-x11-font-utils
    become: yes
    ignore_errors: yes
    package:
      name: font-util
      state: present
  - name: Install fontconfig
    become: yes
    ignore_errors: yes
    package:
      name: fontconfig
      state: present
  - name: Install cabextract
    become: yes
    ignore_errors: yes
    package:
      name: cabextract
      state: present
  - name: install ubuntu utilities
    become: yes
    ignore_errors: yes
    package:
      name:
      - libfreetype6
      - libfreetype6-dev
      - libfontconfig
      state: present
    when: ( ansible_facts['distribution'] == "KDE neon" or ansible_facts['distribution'] == "Ubuntu" )
    
    
  - name: Install Microsoft fonts
    become: yes
    dnf:
      name: https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
      state: "{{ ms_core_fonts }}"
    when: ansible_facts['os_family'] == "RedHat"
    
  - name: Install Microsoft fonts for Suse
    become: yes
    zypper:
      name: fetchmsttfonts
      state: "{{ ms_core_fonts }}"
    when: ansible_facts['distribution_file_variety'] == "SUSE"
    
  - name: Accept License for MS Core Fonts KDE Neon / Ubuntu
    shell: 'echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections'
    when:
      - ( ansible_facts['distribution'] == "KDE neon" or ansible_facts['distribution'] == "Ubuntu" )
      - ms_core_fonts == "present"
      
  - name: Install Microsoft fonts for KDE Neon / Ubuntu
    become: yes
    package:
      name: ttf-mscorefonts-installer
      state: "{{ ms_core_fonts }}"
    when:
      - ( ansible_facts['distribution'] == "KDE neon" or ansible_facts['distribution'] == "Ubuntu" )
      - ms_core_fonts == "present"
      
#
# Install Google Fonts
#

  - name: Create the download directory for the Google fonts
    file:
      path: "{{ user_home_directory }}/Downloads/google-fonts/"
      state: directory
      mode: 0755
    
  - name: Download Google fonts
    block:
      - get_url:
          url: https://github.com/google/fonts/archive/master.tar.gz
          dest: "{{ user_home_directory }}/Downloads/google-fonts/master.tar.gz"
          mode: 0440

      - unarchive:
          src: "{{ user_home_directory }}/Downloads/google-fonts/master.tar.gz"
          dest: "{{ user_home_directory }}/Downloads/google-fonts/"

      - file:
          path: /usr/share/fonts/truetype/google-fonts
          state: directory
          mode: 0755
        become: yes

      - copy: 
          src: "{{ user_home_directory }}/Downloads/google-fonts/fonts-master/apache/"
          dest: /usr/share/fonts/truetype/google-fonts
        become: yes
    when: google_fonts =="present"

  - name: Download Noobslab MacBuntu fonts
    block:
      - get_url:
          url: http://drive.noobslab.com/data/Mac/macfonts.zip
          dest: "{{ user_home_directory }}/Downloads/macfonts.zip"
          mode: 0664
        become: no
      - file:
          path: /usr/share/fonts/truetype/macbuntu-fonts
          state: directory
          mode: 0755
        become: yes
      - unarchive:
          src: "{{ user_home_directory }}/Downloads/macfonts.zip"
          dest: /usr/share/fonts/truetype/macbuntu-fonts
        become: yes
    when: macbuntu_fonts == "present"
    
    
    #- name: Install RHEL extra fonts
      #become: yes
      #state: present
      #ignore_errors: yes
      #package:
        #name:
        #- adobe-source-code-pro-fonts
        #- dejavu-sans-fonts
        #- dejavu-sans-mono-fonts
        #- dejavu-serif-fonts
        #- gnu-free-fonts-common
        #- gnu-free-mono-fonts
        #- gnu-free-sans-fonts
        #- gnu-free-serif-fonts
        #- levien-inconsolata-fonts
        #- liberation-fonts-common
        #- liberation-mono-fonts
        #- liberation-sans-fonts
        #- liberation-serif-fonts
        #- mozilla-fira-mono-fonts
        #- msimonson-anonymouspro-fonts
        #- overpass-fonts
        #- terminus-fonts
    #when: rhel_additional_fonts == "present"
    
  - name: Update the fonts cache
    become: yes
    shell: fc-cache -f > /dev/null
