   - name: update profile
     lineinfile:
       dest: "{{ user_home_directory }}/.bashrc"
       regexp: 'PATH=$PATH:$HOME/.local/bin'
       state: present
       insertafter: EOF
       line: 'PATH=$PATH:$HOME/.local/bin'
