---

    #- name: Install sshuttle via PIP for easy ssh tunnelling
      #pip:
        #name: sshuttle
        #extra_args: --user
      #when: sshuttle == "present"

    - name: Install sshuttle
      become: yes
      ignore_errors: yes
      package:
        name: sshuttle
        state: "present"
      when: sshuttle == "present"
