---

  - name: Add multiple repositories into the same file (1/7)
    become: yes
    zypper_repository:
      name: code
      description: Visual Studio Code
      repo: https://packages.microsoft.com/yumrepos/vscode
      disable_gpg_check: yes
      state: present
      runrefresh: yes
  - name: Add multiple repositories into the same file (2/7)
    become: yes
    zypper_repository:
      name: packages-microsoft-com-prod
      description: packages-microsoft-com-prod
      repo: https://packages.microsoft.com/rhel/7/prod/
      disable_gpg_check: yes
      state: present
      runrefresh: yes
  - name: Add multiple repositories into the same file (3/7)
    become: yes
    zypper_repository:
      name: azure-cli
      description: azure-cli
      repo: https://packages.microsoft.com/yumrepos/azure-cli
      disable_gpg_check: yes
      state: present
      runrefresh: yes
  #- name: Add multiple repositories into the same file (4/7)
    #become: yes
    #zypper_repository:
      #name: snappy
      #description: snappy
      #repo: https://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_15.0
      #disable_gpg_check: yes
      #state: present
      #runrefresh: yes



