---

  - name: Add multiple repositories into the same file (1/7)
    become: yes
    zypper_repository:
      name: code
      description: Visual Studio Code
      repo: https://packages.microsoft.com/yumrepos/vscode
      disable_gpg_check: yes
      state: present
      runrefresh: yes
  - name: Add multiple repositories into the same file (2/7)
    become: yes
    zypper_repository:
      name: packages-microsoft-com-prod
      description: packages-microsoft-com-prod
      repo: https://packages.microsoft.com/rhel/7/prod/
      disable_gpg_check: yes
      state: present
      runrefresh: yes
  - name: Add multiple repositories into the same file (3/7)
    become: yes
    zypper_repository:
      name: azure-cli
      description: azure-cli
      repo: https://packages.microsoft.com/yumrepos/azure-cli
      disable_gpg_check: yes
      state: present
      runrefresh: yes
  - name: Add multiple repositories into the same file (4/7)
    become: yes
    zypper_repository:
      name: snappy
      description: snappy
      repo: https://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_15.0
      disable_gpg_check: yes
      state: present
      runrefresh: yes
  - name: Add multiple repositories into the same file (5/7)
    become: yes
    zypper_repository:
      name: KQ
      description: QT5
      repo: http://download.opensuse.org/repositories/KDE:/Qt5/openSUSE_Leap_15.0
      disable_gpg_check: yes
      state: present
      priority: 75
      runrefresh: yes
  - name: Add multiple repositories into the same file (6/7)
    become: yes
    zypper_repository:
      name: KF
      description: KDEFrameworks
      repo: http://download.opensuse.org/repositories/KDE:/Frameworks5/openSUSE_Leap_15.0
      disable_gpg_check: yes
      state: present
      priority: 75
      runrefresh: yes
  - name: Add multiple repositories into the same file (7/7)
    become: yes
    zypper_repository:
      name: KA
      description: KDEApplications
      repo: https://download.opensuse.org/repositories/KDE:/Applications/KDE_Frameworks5_openSUSE_Leap_15.0
      disable_gpg_check: yes
      state: present
      priority: 75
      runrefresh: yes

      #Now need to run zypper -v dup --allow-vendor-change
