---


  - name: Install xorg-x11-font-utils
    become: yes
    ignore_errors: yes
    package:
      name: font-util
      state: "{{ fontutils }}"
  - name: Install fontconfig
    become: yes
    ignore_errors: yes
    package:
      name: fontconfig
      state: "{{ fontutils }}"
