  - name: Add Non OSS Repository for SUSE Leap 15.0
    become: yes
    zypper_repository:
      name: openSUSE-Leap-Non-Oss
      description: openSUSE-Leap-Non-Oss
      repo: http://download.opensuse.org/distribution/leap/15.0/repo/non-oss/
      disable_gpg_check: yes
      state: present
      runrefresh: yes
